spring:
   datasource:
        url: jdbc:mysql://localhost:3306/cegeka
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
   jpa:
     database-platform: org.hibernate.dialect.MySQL5Dialect
     hibernate:
          show_sql: true
          ddl-auto: update

   jwt:
          secret: blablabl12345blatesteudsad14841221
          tokenValidityInSeconds: 3600